#!/bin/bash

#BSUB -J myjob_sup
#BSUB -n 50
#BSUB -gpu "num=1"
#BSUB -R "span[hosts=1] rusage[mem=3]"
#BSUB -q gpuqueue
#BSUB -W 04:00
#BSUB -o myjob.%J.log


source ~/.bashrc
source activate my_conda_env

python ../plot_tsne_semi.py

conda deactivate
source deactivate
